### ISSUE TITLE
broken high lighting

### ISSUE THREAD

**Issue by palandovalex** [tree-sitter/tree-sitter-bash#151] opened 2023-03-08 06:57 UTC
Problem description
Just see this code fragment:

![Снимок экрана от 2023-03-07 18-31-10](https://user-images.githubusercontent.com/75374436/223469536-c6797d7b-cefd-496d-8422-cdb27f69e261.png)

### Affected language servers

bash

### Steps to reproduce

use such bash code fragment, and you will see it

```bash
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
```

### Actual behavior

syntax highlighting breaks down on the case language construct

### Expected behavior

normal highlighting, NOT WORSE THAN WITH pure neovim!

**Comment by carter-canedy** [comment] 2023-03-08 20:09
I second this, that interpolation string breaks the highlighting for any trailing lines in my .bashrc file. I can't imagine this being a super common snippet, but it should be fixed.

**Comment by verhovsky** [comment] 2023-03-08 20:18
Pasting this into https://tree-sitter.github.io/tree-sitter/playground it's parsed correctly, so it seems like this has been fixed on master but not released yet.

**Comment by carter-canedy** [comment] 2023-05-18 14:26
I don't know what you mean by correctly. If you look at the tree that was generated, it produces an error at the expansion
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/109002822/f12309e1-dac4-4505-969a-fd5fdd02a2a9)

**Comment by carter-canedy** [comment] 2023-05-18 14:28
This is the result of the parser error in nvim:
![image](https://github.com/tree-sitter/tree-sitter-bash/assets/109002822/110ebdcf-fd1c-4348-a9b6-c9356469a44e)

**Comment by Exlll** [comment] 2023-06-16 23:20
This seems to be caused by the `(` and `)` after the `+` in that line. If I remove the braces (or replace them with square brackets), the rest is highlighted correctly, e.g.:

```bash
# PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1" 
PS1="\[\e]0;${debian_chroot:+$debian_chroot}\u@\h: \w\a\]$PS1"
```

**Closed** 2023-08-12 19:45 UTC
