### ISSUE TITLE
Proper highlighting is broken

### ISSUE THREAD

**Issue by sahashirshendu** [tree-sitter/tree-sitter-bash#177] opened 2023-06-01 03:25 UTC
Highlighting breaks after some certain loops,
![2023-06-01_08-53](https://github.com/tree-sitter/tree-sitter-bash/assets/87955430/e627c807-53f6-498c-8d53-a2ed99e36f37)

**Comment by Ordoviz** [comment] 2023-06-02 07:47
Please paste a minimal Bash code snippet that triggers an error on https://tree-sitter.github.io/tree-sitter/playground

**Comment by sahashirshendu** [comment] 2023-06-02 16:46
Here it is:
```bash
colors() {
	local fgc bgc vals seq0
	for fgc in {30..37}; do
		for bgc in {40..47}; do
			fgc=${fgc#37} # white
			bgc=${bgc#40} # black
			vals="${fgc:+$fgc;}${bgc}"
			vals=${vals%%;}
			seq0="${vals:+\e[${vals}m}"
			printf "  %-9s" "${seq0:-(default)}"
			printf " ${seq0}TEXT\e[m"
			printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
		done
		echo; echo
	done
}


# Change the window title of X terminals
case ${TERM} in
	xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|interix|konsole*|contour*|foot*|kitty*|wezterm*)
		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
		;;
	screen*)
		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
		;;
esac

use_color=true

alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less

```

**Comment by Ordoviz** [comment] 2023-06-03 07:53
duplicate of #66

**Closed** 2023-08-12 19:45 UTC
