### ISSUE TITLE
Failed to parse expression >|

### ISSUE THREAD

**Issue by ranebrown** [tree-sitter/tree-sitter-bash#78] opened 2020-04-10 03:40 UTC
Something like this `echo 'lorem ipsum' >| file.txt` results in `Failed to parse expression`

**Comment by skovhus** [comment] 2021-03-27 22:18
I believe this was fixed.

**Comment by verhovsky** [comment] 2022-10-22 19:46
Duplicate of #63. Fixed in #75

**Closed by verhovsky** 2022-10-22 19:46 UTC
